"""cria tabelas iniciais

Revision ID: ae5a2c9fb4d6
Revises:
Create Date: 2026-09-30 01:44:06.046977

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae5a2c9fb4d6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categorias")),
    )
    op.create_index(
        "uq_categorias_nome_lower", "categorias", [sa.literal_column("lower(nome)")], unique=True
    )
    op.create_table(
        "fornecedores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=False),
        sa.Column("telefone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fornecedores")),
        sa.UniqueConstraint("cnpj", name=op.f("uq_fornecedores_cnpj")),
    )
    op.create_index(
        "uq_fornecedores_email_lower",
        "fornecedores",
        [sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "produtos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("preco_custo", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("preco_venda", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "quantidade_em_estoque", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("quantidade_minima", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "data_cadastro",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("fornecedor_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("preco_custo >= 0", name=op.f("ck_produtos_preco_custo_nao_negativo")),
        sa.CheckConstraint("preco_venda >= 0", name=op.f("ck_produtos_preco_venda_nao_negativo")),
        sa.CheckConstraint(
            "quantidade_em_estoque >= 0", name=op.f("ck_produtos_saldo_nao_negativo")
        ),
        sa.CheckConstraint("quantidade_minima >= 0", name=op.f("ck_produtos_minimo_nao_negativo")),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
            name=op.f("fk_produtos_categoria_id_categorias"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fornecedor_id"],
            ["fornecedores.id"],
            name=op.f("fk_produtos_fornecedor_id_fornecedores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_produtos")),
        sa.UniqueConstraint("sku", name=op.f("uq_produtos_sku")),
    )
    op.create_table(
        "movimentacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("produto_id", sa.Integer(), nullable=False),
        sa.Column("fornecedor_id", sa.Integer(), nullable=True),
        sa.Column("tipo", sa.Enum("entrada", "saida", name="tipo_movimentacao"), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column(
            "data", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("observacao", sa.String(length=255), nullable=True),
        sa.CheckConstraint("quantidade > 0", name=op.f("ck_movimentacoes_quantidade_positiva")),
        sa.ForeignKeyConstraint(
            ["fornecedor_id"],
            ["fornecedores.id"],
            name=op.f("fk_movimentacoes_fornecedor_id_fornecedores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["produtos.id"],
            name=op.f("fk_movimentacoes_produto_id_produtos"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movimentacoes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movimentacoes")
    # O tipo enum é criado no upgrade e não é removido junto com a tabela.
    sa.Enum(name="tipo_movimentacao").drop(op.get_bind(), checkfirst=True)
    op.drop_table("produtos")
    op.drop_index("uq_fornecedores_email_lower", table_name="fornecedores")
    op.drop_table("fornecedores")
    op.drop_index("uq_categorias_nome_lower", table_name="categorias")
    op.drop_table("categorias")
    # ### end Alembic commands ###
